### ISSUE TITLE
Error running client.rb

### ISSUE THREAD

**Issue by lincomatic** [glurp/ocpp_simulator#1]
*******************\* stopTransaction ********************
{"TRANSACTIONID"=>"11552", "TAGID"=>"84086", "TIMESTAMP"=>"50409", "METERSTOP"=>
"23990"}
Connect to localhost  => 6060  http://localhost:6060/ocpp
Soap Request: << chargeBoxIdentity=CB1000  MessageID=1466873754047  Address=http
://localhost:9090/ocpp  To=you  Action=/StopTransaction  transactionId=11552  id
Tag=84086  timestamp=50409  meterStop=23990>>
undefined method `[]' for nil:NilClass NoMethodError :
   C:/git/ocpp_simulator/client_soap.rb:40:in`http_post'
   C:/git/ocpp_simulator/client_soap.rb:64:in `csend'
   client.rb:69:in`block in <main>'
   client.rb:64:in `each'
   client.rb:64:in`<main>'

I'm using Ruby 2.3.0

**Comment by glurp** [comment]
restesed now,
all works find :)
